### ISSUE TITLE
Handling throttling 

### ISSUE THREAD

**Issue by prabhakar267** [project-travel-mate/server#1]
For any given user, he must not be able to make more than X calls in Y seconds (X and Y configurable)
Reference: http://www.django-rest-framework.org/api-guide/throttling/

**Comment by mohitkh7** [comment]
I am interested to work on it.

**Comment by mohitkh7** [comment]
I have some doubts
1. Which all views should I cover in throttling ? All Views or some specific views ?
2. What should be throttling rate ? I suggest 100 request/hour per view or 1200 -1500 request/hour for all views.
3. Should I also consider throttling against request from anonymous user ?

**Comment by prabhakar267** [comment]
1. All the views should have a throttling limit
2. I think it should be both
3. Anonymous users can only access sign-up and sign-in APIs so we should consider throttling those for someone making malicious users
