### ISSUE TITLE
[Bug] Get user's friends API returns user's own info also

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/server#100]
Suppose user `x` makes a request to
`trip-friends-all` 

### Expected behaviour
the user should return user's friends

### Actual behaviour
It returns `x` info also along with the user's friends.

**Comment by darthgera123** [comment]
ill work on it

**Comment by darthgera123** [comment]
just a clarification, only the name/username of the members should be returned and not the remaining details right?

**Comment by prabhakar267** [comment]
Response structure is fine, it's just that for every response we are getting the current user's information as well.
If I make a call to this API, I will get my user-object as well which should not happen
