### ISSUE TITLE
[API Request] Email verification

### ISSUE THREAD

**Issue by prabhakar267** [project-travel-mate/server#101]
Whenever a new user signs up, send the user a email ([email reference docs](https://docs.djangoproject.com/en/2.0/topics/email/)) with welcome message with a unique code ([uuid reference docs](https://docs.python.org/2/library/uuid.html))

As a part of this issue
+ User should receive an email from Travel Mate team
+ Store the unique code in the Profile table to be consumed later in the verification flow

**Comment by darthgera123** [comment]
can you please block this one for me. i am just stuck on a small bit of my previous pr but i want to solve a top coder

**Comment by prabhakar267** [comment]
You complete the ongoing issue
I can always make new issues 
We have a lot of ideas that need to implemented

**Comment by darthgera123** [comment]
please assign me this issue

**Comment by darthgera123** [comment]
in this issue, regarding unique code, is this used to activate the account?

**Comment by prabhakar267** [comment]
@darthgera123 It would be used to activate account as of now
Also in the future we can leverage this for forget password functionality
