### ISSUE TITLE
[API Request] API for getting a list of monuments for a given city

### ISSUE THREAD

**Issue by prabhakar267** [project-travel-mate/server#103]
As a part of this issue, search for an existing API that can give us a list of monuments for a city
Integrate with that API and make a GET API that takes `city_id` as input and gives a list of monuments

**Comment by mohitkh7** [comment]
This API can be used to retrieve places worth visiting in a city
`https://maps.googleapis.com/maps/api/place/textsearch/json?query=indore+point+of+interest&language=en&key=xxx`

**Comment by prabhakar267** [comment]
Can be fetched from Places API ([hyperlocal module](https://github.com/project-travel-mate/server/tree/master/api/modules/hyperlocal))
