### ISSUE TITLE
Add a parameter for number of cities in "get-all-cities" API

### ISSUE THREAD

**Issue by prabhakar267** [project-travel-mate/server#11]
Currently `get-all-cities` API doesn't take any parameters and blindly returns a list of the cities in database. Instead take a parameters `k` to signify how many cities are to be returned.

**Comment by mohitkh7** [comment]
I am interested to work on this issue.

**Comment by mohitkh7** [comment]
Shall the parameter `k` be passed as 
* URL Parameter - `api/get-all-cities/k`
or
* GET Paramter - `api/get-all-cities?k=<number>`

**Comment by prabhakar267** [comment]
URL parameter
You can take a look at other APIs [here](https://github.com/project-travel-mate/server/blob/master/api/urls.py)

**Comment by prabhakar267** [comment]
Fixed in #12
