### ISSUE TITLE
[API Request] Get one restaurant 

### ISSUE THREAD

**Issue by prabhakar267** [project-travel-mate/server#110]
For a given restaurant ID, make a GET API using Zomato API in `food` module to given the following output parameters
Make a new class called `ZomatoDetailedResponse` in a new file `zomato_detailed_response.py`

### Input parameters
+ restaurant ID
### Output parameters
+ id
+ name
+ url
+ address
+ latitude
+ longitude
+ average_cost_for_two
+ price_range
+ currency
+ featured_image
+ user_rating_aggregate_rating
+ user_rating_votes
+ is_delivering_now
+ has_table_booking
+ cuisines
+ photo_count
+ phone_numbers 
+ list of photos
  + photo_id
  + photo_url
  + caption
  + likes_count

**Comment by darthgera123** [comment]
i would like to work on this issue

**Comment by darthgera123** [comment]
the api is not returning the list of photos as said in the documentation

**Comment by prabhakar267** [comment]
Maybe try for some restaurant which for sure has some photos

**Comment by darthgera123** [comment]
i tried it out for the one given as example and its not returning the picture
