### ISSUE TITLE
[API Request] Forget password

### ISSUE THREAD

**Issue by prabhakar267** [project-travel-mate/server#115]
Make two GET APIs 
+ One which sends an email to the user with a unique code which should be saved in the database in a new password verification table
Doesn't take any input parameters
+ One which accepts the unique code sent on email and a new password, if the code is correct, then validate the password. If both the things are right, reset the password of the user. Else send a 400 response

**Comment by mohitkh7** [comment]
Can I take up this issue ?

**Comment by mohitkh7** [comment]
Is there any existing module which sends email ?

**Comment by Swati4star** [comment]
Checkout signup module. We send an email to the user on signup.
