### ISSUE TITLE
[API Request] Feedback POST api

### ISSUE THREAD

**Issue by prabhakar267** [project-travel-mate/server#13]
To facilitate [#98](https://github.com/project-travel-mate/Travel-Mate/issues/98), we need to have a new table which stores feedbacks of the user with following fields:
+ feedback id
+ user id
+ created date 
+ feedback text

And a POST API to let client make a call to populate this field

**Comment by mohitkh7** [comment]
I am interested to work on this issue.

**Comment by prabhakar267** [comment]
@mohitkh7 sure you can pick this one

**Comment by prabhakar267** [comment]
Fixed in #23

**Comment by Swati4star** [comment]
@prabhakar267 Share the endpoint & request parameters for this API.

**Comment by prabhakar267** [comment]
Endpoint: `/add-feedback` POST 
with `text` as one of the POST parameters
