### ISSUE TITLE
[Feature Request] Raise an issue, if API key expires

### ISSUE THREAD

**Issue by prabhakar267** [project-travel-mate/server#130]
If the Places API Key expires, server should automatically raise a [GitHub issue](https://developer.github.com/v3/issues/#create-an-issue) asking for updating API key

**Comment by rozig** [comment]
@prabhakar267 do you want to check it in every seconds and if its expired then raises a Github Issue? Or does the API have a webhook for this?

**Comment by pkajaba** [comment]
Hello @prabhakar267, 
I looked into the code and it seems that you are using Places API only here: https://github.com/project-travel-mate/server/blob/638e3d2d8b8244ec0a87d9ca1caaeacd3b4ae587/api/modules/hyperlocal/views.py#L29 Am I right?

Anyways, I was searching through the Places API documentation and I was not able to find any information about expiring of the tokens.
Their API returns `403` in case there is a problem with credentials. See [1] for further reference. 

Could you point me how to replicate event of key expiry? 

[1] https://developer.here.com/documentation/places/topics/http-status-codes.html

**Comment by prabhakar267** [comment]
@rozig I don't think there is any need for checking it every second, only when someone calls the API and we identify there is a potential issue with API key, we can raise a issue (_without spamming the issues panel, ofcourse_)

@pkajaba Yes, the check should be on `403` error code, if there's a problem with the credentials (either expired or something else), we would have to resolve the problem ourselves.

**Comment by pkajaba** [comment]
@prabhakar267 that's great, thanks for your response. 

I will look into it :-)

**Comment by pkajaba** [comment]
@prabhakar267 just one thing - you have to be authorized in order to create an issue. There are several ways how to provide GitHub credentials. Do you prefer generating token or password authorization? 
In both cases, these value will be configurable here: https://github.com/project-travel-mate/server/blob/master/nomad/settings.py

**Comment by prabhakar267** [comment]
You can raise a PR which uses password authorization, I will add the credentials to Production.

**Comment by pkajaba** [comment]
@prabhakar267 you can use either password or token. It does not matter in the end. I have actually used generated token because I use 2-phase auth for my account.

**Comment by prabhakar267** [comment]
Closed with #132
