### ISSUE TITLE
[API Request] API to get the list of upcoming Indian holidays

### ISSUE THREAD

**Issue by prabhakar267** [project-travel-mate/server#131]
Using [timeanddate.com](https://www.timeanddate.com/holidays/india/2018)'s list of Indian holidays, generate a JSON for all the holidays in a given year.
+ Cache the response in order to avoid making repeated calls
+ Use the following structure for response (should be a list of following object):
```
    {
        "date": 1, 
        "day": "Monday", 
        "month": "January", 
        "name": "New Year's Day", 
        "type": "Restricted"
    },
```

**Comment by harsha444** [comment]
will do this

**Comment by sanghisha145** [comment]
I would like to work on this.

**Comment by kishan-1234** [comment]
Done with the logic part. Can you please tell where to host the API or should i just print the o/p list of dictionaries as of now?

**Comment by prabhakar267** [comment]
@harsha444 Can you give the update?
@sanghisha145 If @harsha444 doesn't respond you can take it up
@kishan-1234 The API has to be integrated in the project itself.

**Comment by kishan-1234** [comment]
@prabhakar267 I created the API using flask framework. Following is the first three dicts in o/p

[{"date":"1","day":"Monday","month":"January","name":"New Years Day","type":"Restricted Holiday"},{"date":"14","day":"Sunday","month":"January","name":"Pongal","type":"Restricted Holiday"},{"date":"14","day":"Sunday","month":"January","name":"Makar Sankranti","type":"Restricted Holiday"},]

please tell me if this is fine so tht i can create a PR

**Comment by prabhakar267** [comment]
@kishan-1234 Output looks good, please wait for @harsha444 to respond, If he doesn't respond then you can create an API

**Comment by harsha444** [comment]
@kishan-1234 please go ahead and create a PR, I didn't complete it yet.
