### ISSUE TITLE
[Feature Request] Add email field in "Forget password" APIs

### ISSUE THREAD

**Issue by prabhakar267** [project-travel-mate/server#137]
For [forget password APIs](https://github.com/project-travel-mate/server/blob/3acb1d3309f7613874c46dff933c04366511b7a8/api/urls.py#L35-L37), currently it tries to extract the user email address from request, but the call would be made to this APIs from an unauthenticated user, therefore add another field in the request for email (username)

**Comment by adityatandon007** [comment]
@prabhakar267 what is to be done here. Can you please elaborate. I am new to this. Before picking it up I want to know what is to be done in forget password api

**Comment by rohan033** [comment]
Working on this.

**Comment by amoraitis** [comment]
@rohan033 @prabhakar267 I cannot send request 'api/get-user/(user-email)'

![image](https://user-images.githubusercontent.com/17813786/46904049-103cfe00-cee7-11e8-8939-c490bbc93454.png)

**Comment by rohan033** [comment]
@amoraitis It seems that the 'get-user' feature is only available for authorised users. In the image shown above, go to the Authorization section and select the 'Basic Auth' option and enter your user credentials. 
![image](https://user-images.githubusercontent.com/17281037/46904382-d973e180-cf00-11e8-979f-c77df47a8b2b.png)

**Comment by amoraitis** [comment]
@rohan033 I know how to use authorization, but we need an endpoint, which will inform us if a user exists, given the e-mail. Am I getting this wrong?

**Comment by rohan033** [comment]
@amoraitis Currently we receive an empty body in case when username/mail doesn't exist.
We might not require a new end point, instead throw an exception for such cases.
You can raise an issue regarding this and start working on it.

**Comment by Swati4star** [comment]
@amoraitis `api/get-user/(user-email)` should work with authorization only.

You don't need above API to verify user's email.
Just call this API
`https://project-travel-mate.herokuapp.com/api/forgot-password-email-code/<email>`

if email is valid, the response is "Email sent", else it is "Invalid username"
I think this should solve your issue.

**Comment by rohan033** [comment]
@Swati4star What should happen when there is 'user-email' doesn't exist? Currently we get an empty body. Shouldn't we throw an exception?

**Comment by Swati4star** [comment]
Actual empty array is also fine.

This API is actually is also used for getting all the user's whose emial id start with a particular key. For example,
https://project-travel-mate.herokuapp.com/api/get-user/swa

So, in this case, an empty array makes sense

**Comment by rohan033** [comment]
@amoraitis I hope @Swati4star made it clear.

**Comment by amoraitis** [comment]
@Swati4star @rohan033 ok, i see, i thought i could use /get-user endpoint
