### ISSUE TITLE
[API Request] Add an API to send a verifcation code to user

### ISSUE THREAD

**Issue by prabhakar267** [project-travel-mate/server#143]
Create a `GET` API for sending a 6 character verifcation code (generated using [`generate_random_code`](https://github.com/project-travel-mate/server/blob/f989df143e4fb6cb91e9e21bf4e546507feabd17/api/modules/users/utils.py#L6))

+ Create a field in [Profile Model](https://github.com/project-travel-mate/server/blob/master/api/modules/users/model.py#L8) to store verification code
+ Add a template in [email templates](https://github.com/project-travel-mate/server/blob/f989df143e4fb6cb91e9e21bf4e546507feabd17/api/modules/email/templates.py)
+ Add API endpoint in [users modules](https://github.com/project-travel-mate/server/blob/master/api/modules/users/views.py)

**Comment by neequole** [comment]
@prabhakar267 Hi, would like to give this a shot. Can you give me context on this feature like where would this be used,  what is the difference between the `PasswordVerification` model? 

* Create a field in Profile Model to store verification code - are you sure to put it here?
         - if yes, should we add a created_at field? 
         - if not, should we create a new model like the PasswordVerification?

**Comment by prabhakar267** [comment]
@neequole You can use the `PasswordVerification` model, it was meant for this feature only. 
You should add a `created_at` field.
