### ISSUE TITLE
[API Request] Add an API to verify user

### ISSUE THREAD

**Issue by prabhakar267** [project-travel-mate/server#146]
Add a GET API in users module which takes `verification_code` as parameter and matches it with code from `PasswordVerification` table. 
If the code matches, set `is_verified` flag as true in `Profile` table.

### Tasks to be done for this issue
+ Add API to take `verification_code`
+ Match verification_code from `PasswordVerification` table
+ Set `is_verified` flag as true in `Profile` table if code matches
+ Send appropriate response if code doesn't match

**Comment by vhugo** [comment]
I'd like to work on this.
