### ISSUE TITLE
[API Request] GET API to check PNR status

### ISSUE THREAD

**Issue by prabhakar267** [project-travel-mate/server#15]
Using [RailwayAPI](https://railwayapi.com/api/#pnr-status), have a GET endpoint to check PNR status for any given input string.
#### Input fields
+ PNR string
#### Output
+ Same response as RailwayAPI

**Comment by mohitkh7** [comment]
RailwayAPI requires an [api-key] with each request. How to get it ?

**Comment by mohitkh7** [comment]
@prabhakar267  do I need to get new api-key or is there existing key for this project ?

**Comment by prabhakar267** [comment]
Closing this since, we are not planning to implement it currently 
/cc @Swati4star
