### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by Rudloff** [project-travel-mate/server#153]
Hello,

I did not find any license file in this repository.
Would it be possible to clarify the license of this source code? Is it MIT like the Android app?

**Comment by Swati4star** [comment]
Yes. It is MIT only. Added in https://github.com/project-travel-mate/server/commit/4ca2666cd49694245aeee0e658bf5ebce448e50e

**Comment by Rudloff** [comment]
Thank you for the clarification!
