### ISSUE TITLE
Google Map API

### ISSUE THREAD

**Issue by GouravSardana** [project-travel-mate/server#156]
Hemabh has completed the assigned API work. Is there is any thing to add up?

**Comment by HemabhKamboj** [comment]
Travis build is failing due to warnings of psycong2 wheel library.
shall I change requirements.txt

**Comment by GouravSardana** [comment]
Yeah you can change the requirements.txt. so that travis build will get success

**Comment by prabhakar267** [comment]
This has been fixed. Closing the issue
