### ISSUE TITLE
[API Request] Remove friend from a trip

### ISSUE THREAD

**Issue by prabhakar267** [project-travel-mate/server#16]
Currently you can only [add a friend to a trip](https://github.com/project-travel-mate/server/blob/master/api/modules/trips/views.py#L75), now a GET API is needed to remove a friend from a given trip.
Check if the currently logged in user is authorized (part of the trip) or not.
### Input Parameters
+ trip id
+ user (to be removed) id
### Response codes
+ 200 (successfully removed)
+ 404 (user or trip not found)
+ 401 (unauthorized user)

**Comment by akansha006** [comment]
I would like to work on this issue.

**Comment by IHackPy** [comment]
Sure Akansha you can start work on that If having any issue ping us here or on slack :+1:

**Comment by Swati4star** [comment]
@prabhakar267 what is the endpoint for this?
