### ISSUE TITLE
[Feature Request] Add number of verified users in analytics API

### ISSUE THREAD

**Issue by prabhakar267** [project-travel-mate/server#160]
Currently the response from [`get_total_users`](https://github.com/project-travel-mate/server/blob/master/api/modules/analytics/views.py) API in `analytics` module does not have a field for number of verified users.

### Expected behaviour
Add a new field in response to show number of verified users.

**Comment by sumit-badsara** [comment]
@prabhakar267 I have added extra response `active_verified_users` with `verified_users`. If that is not required. Please tell me, I will create a new PR, with required changes.

**Comment by prabhakar267** [comment]
@BadduCoder Merged PR. Great work 👍
