### ISSUE TITLE
Profile image in user table

### ISSUE THREAD

**Issue by prabhakar267** [project-travel-mate/server#17]
Change user model to add profile image url in the users table and add the `profile_image` field in [`UserSerializer`](https://github.com/project-travel-mate/server/blob/master/api/modules/users/serializers.py#L7)
By default have a `null` value in `profile_image`
Also have a POST API to allow user to update his profile picture which takes input profile image url

**Comment by mohitkh7** [comment]
can i work on this issue ?

**Comment by prabhakar267** [comment]
@mohitkh7 sure

**Comment by prabhakar267** [comment]
@mohitkh7 You can read [this](https://simpleisbetterthancomplex.com/tutorial/2016/07/22/how-to-extend-django-user-model.html) blogpost and get a help on how to do the fix
I'd prefer **Option 2**: Using One-To-One Link With a User Model (Profile)
