### ISSUE TITLE
[Documentation] Add instructions for adding city information to database

### ISSUE THREAD

**Issue by prabhakar267** [project-travel-mate/server#170]
There are no APIs to add a new city to the database, so in order for someone to test any city API, they need to either use some Postgres UI application or use PS CLI. Easiest way being Django admin dashboard.

In order to add a new city using Django admin, someone needs to create a Django superuser, run application and then add City information.

Add instructions in Troubleshooting guide for the same.

**Comment by annp89** [comment]
Hi! 
I'd like to contribute to this ask. 

Is the ask adding a new section in https://github.com/project-travel-mate/server/blob/master/TROUBLESHOOTING.md explaining how to access Django admin by creating a superuser and access the City table to add data in there for testing? 

Would you like the docs for the superuser setup be added to the README.md file as well?
