### ISSUE TITLE
[Enhancement] Add a validation for email address in validate_email

### ISSUE THREAD

**Issue by prabhakar267** [project-travel-mate/server#172]
Currently we have only one validation for email address verification in `validate_email` which is if `@` is present in string or not. We can use [`parseaddr`](https://stackoverflow.com/a/14485817) Python util to check if the string is a valid email address or not.

+ Add a new validator in [`users.validators`](https://github.com/project-travel-mate/server/blob/master/api/modules/users/validators.py) to use `parseaddr`
+ Add unit tests for the same in [`test_validators`](https://github.com/project-travel-mate/server/blob/master/tests/users/test_validators.py)

**Comment by fsjoyti** [comment]
Can I take this one up? I would like to give it a shot.

**Comment by prabhakar267** [comment]
@fsjoyti sure.

**Comment by prabhakar267** [comment]
Fixed in #175
