### ISSUE TITLE
[API Request] Get user by ID

### ISSUE THREAD

**Issue by prabhakar267** [project-travel-mate/server#18]
A GET API to get all the details of the user using `user_id`
Reference Code: [User table interactions](https://github.com/project-travel-mate/server/blob/master/api/modules/users/views.py#L61) and [handling primary key](https://github.com/project-travel-mate/server/blob/master/api/modules/city/views.py#L27)

**Comment by mohitkh7** [comment]
I will like to work on this issue.

**Comment by mohitkh7** [comment]
Shall the details of staff user and superuser restricted like done over [here](https://github.com/project-travel-mate/server/blob/master/api/modules/users/views.py#L68).

**Comment by prabhakar267** [comment]
If you are picking by ID, I don't think these permissions make any difference. 
You can return the user object regardless of these permissions.

**Comment by prabhakar267** [comment]
Closed in #22
