### ISSUE TITLE
Add virtualenv instructions for Windows

### ISSUE THREAD

**Issue by nikochiko** [project-travel-mate/server#181]
Describe your issue here.

### Steps to reproduce
reference: https://github.com/project-travel-mate/server/blob/master/README.md#local-setup-instructions

### Expected behaviour
As the Postgres step includes instructions for both Linux and Windows, the virtualenv step should also include instructions for both.

### Actual behaviour
Currently, the readme (only contains virtualenv instructions for Linux (the `source` command).

### Would you like to work on the issue?
Yes, I would like to submit a quick fix.

**Comment by prabhakar267** [comment]
@nikochiko Can you raise a PR for the same?

**Comment by nikochiko** [comment]
@prabhakar267 I've added the PR! I got a bit distracted in between so sorry for the delay.
