### ISSUE TITLE
not working 

### ISSUE THREAD

**Issue by projectworldsofficial** [project-travel-mate/server#186]
Describe your issue here.

### Steps to reproduce
i am not know
![5e32e8ff-3d31-4f8e-93f3-f5d20371e6e1](https://user-images.githubusercontent.com/33458568/75901437-80de1500-5e64-11ea-88d4-dafa324a7dc6.png)
![077e4f40-58cb-4f3f-aef7-f1996854c93a](https://user-images.githubusercontent.com/33458568/75901496-9ce1b680-5e64-11ea-80bc-743073c81e30.png)
![6a5af006-6b9f-420c-9c88-857c70c9eea3](https://user-images.githubusercontent.com/33458568/75901538-abc86900-5e64-11ea-8494-5cda9a63ba48.png)
![1ba8f242-4a47-46fa-b0bf-df2c6c2bc76f](https://user-images.githubusercontent.com/33458568/75901564-b8e55800-5e64-11ea-9d8b-d1ffa2be7807.png)

### Expected behaviour

like demo app

### Actual behaviour

my api- https://travelbuddyss.herokuapp.com/api/

origianl api - https://project-travel-mate.herokuapp.com/api/

i have use original api then android app working fine 
but same time using my api login register work but then another
search city work selected but unexpected app stopped or close 
please inspect my demo link what isssue i an not understand 
i have follows all steps perfectly step by step issue same 
what issue ?? database issue or any other please help..

demo link - https://travelbuddyss.herokuapp.com/admin

admin username - admin
admin password - Yugesh123

Postgres Database details

DATABASE_NAME  -  d5805jslspmqnm

DATABASE_USER   - amxadwshqsrmnl

DATABASE_PASS  - 3c4baca2332bfe507ea963d75d7a0925bc6f2429b5c60b532cd884cf7da4cce7

DATABASE_HOST  - ec2-52-202-185-87.compute-1.amazonaws.com

### Would you like to work on the issue?

please tell me solution

**Comment by prabhakar267** [comment]
@projectworldsofficial I can clearly see, you are trying to create a knock off for Travel Mate and very creatively are calling it "Travel Buddy". Now that you are not able to even copy the complete source code provided, do you really expect us to help you with the issue?

If you want to use Travel Mate or its source code for educational purposes please email us at projecttravelmate.github.io@gmail.com and let us know how are going to use the source code and based on the mail we might be able to help you. Thanks.
