### ISSUE TITLE
[API_REQUEST](New) city (names) do not fetch data from Wiki

### ISSUE THREAD

**Issue by alfje2000** [project-travel-mate/server#189]
Some cities I create does not fetch (extract) data from WIKI
When I click 'Know more about ...." in the app then no data is fetched.
Mainly small cities....and with the exact API wiki call given in the Internetbrowser it works with that city.

How come?

**Comment by prabhakar267** [comment]
@alfje2000 Can you gave the name of any city or any city ID which shows this error

**Comment by alfje2000** [comment]
I created some dutch cities 'Enschede and Deventer'...and more.... When i click Know more about this city it keeps searching. Other cities I created for example Almelo do fetch this data correct.
