### ISSUE TITLE
Caching external API call responses

### ISSUE THREAD

**Issue by prabhakar267** [project-travel-mate/server#19]
For all the external API call responses ([get-shopping-info](https://github.com/project-travel-mate/server/blob/master/api/urls.py#L34), [get-city-weather](https://github.com/project-travel-mate/server/blob/master/api/urls.py#L29), [get-city-trends](https://github.com/project-travel-mate/server/blob/master/api/urls.py#L26), etc.), we need to cache their responses to make efficient usage of API calls made externally.
There is an existing package that allows us to have a caching layer for all calls made using `requests` package.
Reference: [Requests-cache](http://requests-cache.readthedocs.io/en/latest/index.html) or [Django’s cache framework](https://docs.djangoproject.com/en/2.0/topics/cache/)

**Comment by mohitkh7** [comment]
@prabhakar267 What is the reason for preferring [Requests-cache](http://requests-cache.readthedocs.io/en/latest/index.html) and not [Django's Cache Framework](https://docs.djangoproject.com/en/2.0/topics/cache/)

**Comment by prabhakar267** [comment]
No preference
