### ISSUE TITLE
[API_REQUEST]I want to fetch city data from WIKI in other language

### ISSUE THREAD

**Issue by alfje2000** [project-travel-mate/server#190]
I tried to fetch data in other language from WIKI

I changed the 
wiki_api_url = "https://en.wikipedia.org/w/api.php" + \
                       "?action=query&prop=extracts&explaintext&titles=" + \
                       city.city_name + \
                       "&format=json"

into

wiki_api_url = "https://nl.wikipedia.org/w/api.php" + \
                       "?action=query&prop=extracts&explaintext&titles=" + \
                       city.city_name + \
                       "&format=json"

After that nothing is shown and fetched from this site in the app when i click 'know more about ...' a city.

**Comment by Swati4star** [comment]
@alfje2000 what response are you getting with the second API?

**Comment by alfje2000** [comment]
@Swati4star ...I commented this issue also in the android app section. It must me something with json parsing. The app does not respond on this and shows the animated blue picture.
