### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by prabhakar267** [project-travel-mate/server#2]
All the `get` APIs which return more than one results should be paginated and the request and response objects should be indicative of the same
Reference: http://www.django-rest-framework.org/api-guide/pagination/

**Comment by mohitkh7** [comment]
I want to work on this issue.

**Comment by prabhakar267** [comment]
I don't think client is mature enough to handle this
I'd suggest you pick something else
Because anyways I won't be able to merge it until client has pagination capabilities

**Comment by mohitkh7** [comment]
ok

**Comment by prabhakar267** [comment]
@mohitkh7 if you want to work on this, you can do it now.

**Comment by mohitkh7** [comment]
Since we are not using class based views in our project we can't set pagination globally. 
We will have to change every view as follows - 
<pre><code>@api_view(['GET'])
def get_all_cities(request, no_of_cities=8):
    cities = City.objects.annotate(visit_count=Count('logs')).order_by('-visit_count')[:no_of_cities]
    # pagination begin
    paginator = PageNumberPagination()
    paginator.page_size = 10
    cities_paginated = paginator.paginate_queryset(cities, request)
    serializer = CityCondensedSerializer(cities_paginated, many=True)
    return paginator.get_paginated_response(serializer.data)</code></pre>

@prabhakar267 is there any better approach ? or shall I implement it ?

**Comment by prabhakar267** [comment]
I can't think of anything better
Clearly it seems like we should have started with class based views, but it would be too much effort to port to class based views now
