### ISSUE TITLE
[API Request] Call GitHub APIs to get a list of the users who have worked on project

### ISSUE THREAD

**Issue by prabhakar267** [project-travel-mate/server#20]
For all the repositories in the [organisation Project Travel Mate](https://github.com/project-travel-mate), make a call to [List contributors GitHub API](https://developer.github.com/v3/repos/#list-contributors) and fetch all the users who have worked on developing various projects sorted in the order of their `contributions`. Include following fields for each of contributor object.
+ GitHub username
+ GitHub URL
+ Contributions
+ Projects contributed to (server / android) 
+ Avatar URL

**Comment by Pradhvan** [comment]
@prabhakar267 can I take this issue up ?

**Comment by prabhakar267** [comment]
@Pradhvan sure

**Comment by brijeshshah13** [comment]
@Swati4star @prabhakar267 I think we should display contributors of each repo. in the respective app. I mean displaying contributors who contributed to android app here and vice-versa doesn't add up. That will infact create more problems in searching for actual contributors of the respective repo.

**Comment by Swati4star** [comment]
We can have different APIs for contributors of Android repo & server repo.
We can show both in the app under different headings.

**Comment by brijeshshah13** [comment]
@Swati4star So in android app, we will display contributors of android repo and server repo separately under different headings and in descending order of number of contributions, correct?

**Comment by Swati4star** [comment]
Yes.

**Comment by brijeshshah13** [comment]
@Swati4star Also, I don't think we need to add Display name as we are already showing the github username along with the profile URL. That will only add the overhead of calling one more API call as the Display name isn't included in the response.

Sample response of each contributor:

```
    {
        "login": "prabhakar267",
        "id": 10768588,
        "node_id": "MDQ6VXNlcjEwNzY4NTg4",
        "avatar_url": "https://avatars2.githubusercontent.com/u/10768588?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/prabhakar267",
        "html_url": "https://github.com/prabhakar267",
        "followers_url": "https://api.github.com/users/prabhakar267/followers",
        "following_url": "https://api.github.com/users/prabhakar267/following{/other_user}",
        "gists_url": "https://api.github.com/users/prabhakar267/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/prabhakar267/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/prabhakar267/subscriptions",
        "organizations_url": "https://api.github.com/users/prabhakar267/orgs",
        "repos_url": "https://api.github.com/users/prabhakar267/repos",
        "events_url": "https://api.github.com/users/prabhakar267/events{/privacy}",
        "received_events_url": "https://api.github.com/users/prabhakar267/received_events",
        "type": "User",
        "site_admin": false,
        "contributions": 23
    },
```

**Comment by brijeshshah13** [comment]
@Swati4star Any updates on the above suggestion?

**Comment by prabhakar267** [comment]
@brijeshshah13 Let's remove display name

**Comment by brijeshshah13** [comment]
@prabhakar267 Cool. @Swati4star Please take a note of this while designing the UI for the android app.

**Comment by brijeshshah13** [comment]
@prabhakar267 Is is really necessary to implement this API endpoint in our server as that will too you call the GitHub end-point and forward the same response. Can we directly call it from the app itself?

**Comment by prabhakar267** [comment]
You need to compute this list once and use it multiple times
This computation can be cached on the server, saving the API calls to GitHub

**Comment by brijeshshah13** [comment]
The GitHub end-point already does the caching. `This endpoint may return information that is a few hours old because the GitHub REST API v3 caches contributor data to improve performance.`, as stated in the docs.

**Comment by brijeshshah13** [comment]
@prabhakar267 @Swati4star Please let me know your final decision, i.e., if it is still going to be implemented in our server or not?

**Comment by Swati4star** [comment]
@brijeshshah13 This will be implemented in the server.
It would become messed up in our code to get the contributors for server & android repo individually, whereas if it will be implemented by our server, we will have a consolidated list for both.

The caching will also be more effective if it's implemented in our server (@prabhakar267 can explain better)

**Comment by brijeshshah13** [comment]
@Swati4star Cool ! Meanwhile, can I take up another issue as it can't implemented in app until the end-point is incorporated in the server?

**Comment by prabhakar267** [comment]
@Pradhvan status?

**Comment by mohitkh7** [comment]
if @Pradhvan is not working on this issue anymore, can I take this up ?

**Comment by prabhakar267** [comment]
@Pradhvan has been inactive for quite sometime, assigning it to @mohitkh7

**Comment by mohitkh7** [comment]
@prabhakar267 kindly review the changes.

**Comment by Swati4star** [comment]
@prabhakar267 @mohitkh7 What is the final endpoint for this API?
cc/ @brijeshshah13

**Comment by mohitkh7** [comment]
The final endpoint for api is 
`/api/get-contributors/<project_name>`
e.g. 
`/api/get-contributors/server`

the output will be in following format 
```
[
    {
        "avatar_url": "https://avatars2.githubusercontent.com/u/10768588?v=4",
        "contributions": 32,
        "url": "https://github.com/prabhakar267",
        "username": "prabhakar267",
        "repository_name": "server"
    },
    {
        "avatar_url": "https://avatars1.githubusercontent.com/u/19525624?v=4",
        "contributions": 14,
        "url": "https://github.com/mohitkh7",
        "username": "mohitkh7",
        "repository_name": "server"

    },
    .  
    .   
    .  
]  
```
