### ISSUE TITLE
[API Request] Get all feedbacks of user and get one feedback by feedback id

### ISSUE THREAD

**Issue by prabhakar267** [project-travel-mate/server#24]
We have a feedback model, make two GET apis
### Get all feedbacks
API to get a list of all the feedbacks for a given user
#### Outputs
List of feedback objects sorted in descending order of time, which includes feedback ID, feedback type and date 

### Get all feedbacks
API to get feedback object for a given feedback ID
Check if the user is authenticated to view this feedback or not
#### Input parameter
+ Feedback ID 
#### Outputs
Feedback object including feedback ID, feedback text, feedback type and date

**Comment by arunikayadav42** [comment]
Can I start working on this issue please :)

**Comment by darthgera123** [comment]
@arunikayadav42 please let me work on this lol

**Comment by arunikayadav42** [comment]
Sure :) you don't need my permission to :+1:

**Comment by darthgera123** [comment]
there is no feedback id in the table, so i am creating one. Also how do i test my querries?

**Comment by Swati4star** [comment]
@prabhakar267 Mention the endpoint of this API.
