### ISSUE TITLE
Include "feedback type" in feedback model

### ISSUE THREAD

**Issue by prabhakar267** [project-travel-mate/server#26]
The Feedback model needs to have another field `feedback type`
Add this field in the [add-feedback](https://github.com/project-travel-mate/server/blob/master/api/modules/feedback/views.py#L9) POST api as well

**Comment by mohitkh7** [comment]
I am interested to work on it.

**Comment by mohitkh7** [comment]
I assume feedback type should be a choice field. 
What all choices should it have ? Any reference for it ?

**Comment by prabhakar267** [comment]
You can consider it as an string input you will get in API call
_ENUM-ification_ of that can be handled on client side
(sounds right @Swati4star ?)

**Comment by mohitkh7** [comment]
@prabhakar267 what should be default feedback type ?

**Comment by prabhakar267** [comment]
Currently there are 3 types: `Crash`, `Feature Request`, `Other`

You can have `Other` as default
But it should be a required parameter in POST API
