### ISSUE TITLE
[API Request] GET API for currency convertor

### ISSUE THREAD

**Issue by prabhakar267** [project-travel-mate/server#27]
Using [The Free Currency Converter API](https://free.currencyconverterapi.com) make a GET API that takes two currencies, `source_currency` and `target_currency` and make a call to the API and render the conversion rate as output

**Comment by arunikayadav42** [comment]
Can I get started with this issue please :)

**Comment by arunikayadav42** [comment]
Also if you could help me get started Like I only know a bit of django and am still learning the same so any help would be appreciated...

**Comment by arunikayadav42** [comment]
@prabhakar267 also on this issue..can I work on this issue too :)

**Comment by prabhakar267** [comment]
@arunikayadav42 You complete one issue, then you can pick other 👍 
We have a plenty of issues, don't worry

**Comment by darthgera123** [comment]
is this issue assigned or can i work on this?

**Comment by prabhakar267** [comment]
@darthgera123 you can work on this

**Comment by arunikayadav42** [comment]
@prabhakar267 actually this was a good first issue so I wanted to start off with this one if it's alright :)

**Comment by arunikayadav42** [comment]
Moreover @prabhakar267 I have already started working on this one so if you could please offer @darthgera123 some other issue :)

**Comment by prabhakar267** [comment]
@arunikayadav42 please claim only one issue at a time
Once you fix that or release it for someone else, then only claim another one
There are a lot of people wanting to work on the project, let's maintain the basic OSS courtesy
Thanks

Making an exception for this time since you have started working on the issue. You would have to complete this issue before you claim any other issue. PRs by you for any other issues would be rejected right away. 

For @darthgera123 , you can pick #24 
No one is working on that 😄 
/cc @Swati4star

**Comment by darthgera123** [comment]
no problem

**Comment by arunikayadav42** [comment]
@prabhakar267 when I am trying to run python manage.py test it gives me the following error.
![screenshot from 2018-06-27 02-58-45](https://user-images.githubusercontent.com/28708494/41940400-3bf812cc-79b6-11e8-9fce-a8c986726678.png)
Please help me.

**Comment by arunikayadav42** [comment]
@prabhakar267 any comments on the above error ?

**Comment by prabhakar267** [comment]
@arunikayadav42 I faced the same issue, I don't remember exactly what I did to fix it
You can have a look at this answer https://stackoverflow.com/a/14186439/5602759
I remember this solved my problem

**Comment by prabhakar267** [comment]
@arunikayadav42 updates?

**Comment by arunikayadav42** [comment]
I am still trying to dealing with that error....

**Comment by prabhakar267** [comment]
Ping me on slack

**Comment by darthgera123** [comment]
its simple you can log into the postgres shell and type ALTER USER nomad CREATEDB; and it works like a charm

**Comment by arunikayadav42** [comment]
I will try to look into it again today :)

**Comment by prabhakar267** [comment]
@darthgera123 can you raise a PR with this in README?

**Comment by arunikayadav42** [comment]
Can I raise it?

**Comment by darthgera123** [comment]
sure

**Comment by arunikayadav42** [comment]
Can somebody tell me that even after running localhost:8000 in the browser I dont see anything running.why is it so?

**Comment by arunikayadav42** [comment]
@prabhakar267 I need your help please how do I connect with you on slack please let me know!

**Comment by arunikayadav42** [comment]
Also does it have to be a separate api directory or will it be inserted in the views.py module of existing apis?

**Comment by prabhakar267** [comment]
@arunikayadav42 are you working on this as a part of GSSoC?
If so you would have had gotten a invitation for slack channel
If not, you can ping me on Hangouts (prabhakargupta267@gmail.com)
