### ISSUE TITLE
[API Request] Get profile API

### ISSUE THREAD

**Issue by prabhakar267** [project-travel-mate/server#28]
API to get profile of the signed in user similar to `get-user-by-id`
+ Takes no input ( use `request.user` to get current user object)
+ Return UserSeralizer response

**Comment by Swati4star** [comment]
send `joined_on` also in the response.

**Comment by arunikayadav42** [comment]
Is anybody working on this issue or can I get started with it please :)

**Comment by prabhakar267** [comment]
@arunikayadav42 You can work on this 👍
