### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by prabhakar267** [project-travel-mate/server#3]
+ Sign in and sign up APIs 
+ Authorization of user info before accessing every other API
+ Sending `401` for unauthorized users

**Comment by lavishsaluja** [comment]
Hi, Can I work on it? Can you tell me what do I need to learn exactly for building the Oauth there and what all should I refer?
PS: I am very new to development (this is my first time to open source) and have made a simple blog application using Django and some other simple web apps.

**Comment by prabhakar267** [comment]
@lavishsaluja someone (@AnirudhGoel ) is already working on this issue, you can probably work on something else.
