### ISSUE TITLE
"created_at" in user table

### ISSUE THREAD

**Issue by prabhakar267** [project-travel-mate/server#30]
Change user model to add profile `created_at` in the users table and add it in UserSerializer
For current entries, set the `created_at` time to `now`.

**Comment by techac** [comment]
i want to work on this

**Comment by prabhakar267** [comment]
@techac sure
You `date_joined` field in User table to achieve this, I don't think there's any need to generate a new field

**Comment by techac** [comment]
@prabhakar267  so date_field is by default is set as time.now so do you  want me to include it in serialisers

**Comment by prabhakar267** [comment]
@techac Yes

**Comment by techac** [comment]
@prabhakar267  sir i as this my first PR so i have some doubts 
like for experiment i created new superuser to DB so do everytime i need to delete the user and then commit changes for PR .. Plz help tq

**Comment by prabhakar267** [comment]
@techac Let's connect on the slack channel

**Comment by techac** [comment]
![screenshot from 2018-06-28 19-55-44](https://user-images.githubusercontent.com/33215722/42040466-4dfc1c7c-7b0d-11e8-86c1-b0b226497ae3.png)
@prabhakar267  why i am getting this error i was not getting it previously....

**Comment by prabhakar267** [comment]
Do you have the latest commits locally?

**Comment by techac** [comment]
yes

**Comment by prabhakar267** [comment]
`python manage.py migrate`

**Comment by techac** [comment]
hello actually there was a problem inn ubuntu version.... dpkg 
PR made #40 for review

**Comment by prabhakar267** [comment]
Fixed in #40 
Thanks to @techac
