### ISSUE TITLE
[API request] Get nearest tourist attractions like monuments or parks given a pair of coordinates

### ISSUE THREAD

**Issue by prabhakar267** [project-travel-mate/server#4]
Given a pair of coordinates and a parameter `k`, return nearest `k` results of tourist attractions stored in a table sorted in ascending order by the distance from the given coordinates.
Each attraction object must contain:
 + exact coordinates
 + icon
 + name of the place
 + calculated distance from given coordinates

**Comment by lavishsaluja** [comment]
Can I work on this considering I am a beginner but I am ready to learn the implementation of algorithm required? I will probably need help in doing this I really want to implement this feature.

**Comment by prabhakar267** [comment]
@lavishsaluja  Sure, you can work on this
Let me know if you need any help

**Comment by lavishsaluja** [comment]
Haha, I will need complete help as of now. This is my first step. How will I come to know which part of code I have to change and link to the new functions? I mean how do people get to understand a big code base? What least I should understand to start working on this in technologies?

**Comment by lavishsaluja** [comment]
Hi, Can we use this [Places API](https://developers.google.com/places/web-service/intro) or we want to build a similar service for our server?

**Comment by prabhakar267** [comment]
Fixed in [d77f7b36a822720789da9dcdf98186524d54dad9](https://github.com/project-travel-mate/Travel-Mate/commit/d77f7b36a822720789da9dcdf98186524d54dad9)
