### ISSUE TITLE
[API Request] Add home route and 404 routes

### ISSUE THREAD

**Issue by prabhakar267** [project-travel-mate/server#41]
Currently we don't have a 404 route or home route.
+ For 404 route, we should be **permanently** redirecting the user to home route.
+ For home route (`/`), we redirect the user to [Travel mate website](http://project-travel-mate.github.io/Travel-Mate)

**Comment by arunikayadav42** [comment]
I would want to take up this issue :)

**Comment by arunikayadav42** [comment]
Does this mean that when django throws a 404 error we should redirect him to home page ?where do I exactly start working on this?

**Comment by arunikayadav42** [comment]
do we have to use routers?
