### ISSUE TITLE
[API Request] Call GitHub APIs to get a list of all the current open issues for org

### ISSUE THREAD

**Issue by prabhakar267** [project-travel-mate/server#44]
For all the repositories in the [organisation Project Travel Mate](https://github.com/project-travel-mate), make a call to [List issues for a repository GitHub API](https://developer.github.com/v3/issues/#list-issues-for-a-repository) and fetch all the currently open issues. Include following fields for each object.
+ Issue title
+ Created at
+ Number of comments 
+ Repository URL 
+ Issue number
+ Tags

**Comment by techac** [comment]
@prabhakar267 i want to work on this issue but can you give me guidance of how it will be implemented and give me some resources which i can refer to... thks...

**Comment by prabhakar267** [comment]
@techac You can have a look at #64
