### ISSUE TITLE
[API Request] Get all visited cities with count

### ISSUE THREAD

**Issue by prabhakar267** [project-travel-mate/server#45]
Return a list of all the cities visited (trip) by a user along with the number of times he visited them.
Pick the user id from `request`
Output should a list of objects, each containing following information
+ city object
+ count

**Comment by techac** [comment]
@prabhakar267 i want to work on this

**Comment by techac** [comment]
@prabhakar267  i am thinking to implement it by making model with two foreign keys, one to City and other to user ......then make the desirable view and serializer... Is this Okay? or should I implement it in more nicer way?....Do suggest...tks

**Comment by prabhakar267** [comment]
There is a model [CityVisitLog](https://github.com/project-travel-mate/server/blob/master/api/modules/city/model.py#L27) which has this information 
Try to leverage that instead of making a new one

**Comment by techac** [comment]
you may review changes now

**Comment by techac** [comment]
you may review pull request #69 for approval
