### ISSUE TITLE
[API Request] Store "checklist" information in database to sync

### ISSUE THREAD

**Issue by prabhakar267** [project-travel-mate/server#46]
Expose 2 APIs (`GET` and `POST`) to store and serve checklist information from user.
Create new checklist table with following fields
+ user
+ checklist_items
+ last_updated

On every POST call, you will get a list of all the checklist items, you can store the complete response as a field in table.
For GET API, you need to return the checklist object, with above attributes

**Comment by iamdaaniyaal** [comment]
@prabhakar267 Is this issue resolved??
If not I would like to work on it

**Comment by iamdaaniyaal** [comment]
@prabhakar267 
last_updated is a timestamp field?

**Comment by prabhakar267** [comment]
Yes

**Comment by prabhakar267** [comment]
@iamdaaniyaal updates?

**Comment by darthgera123** [comment]
can i work on this issue

**Comment by darthgera123** [comment]
so do you want me to extend the Profile class i.e add 2 new columns or create an entirely new table with columns as user, timestamp and checklist

**Comment by darthgera123** [comment]
also in what format do you want the time to be stored?

**Comment by prabhakar267** [comment]
I think a new table would make more sense since `Profile` table should be user details related.
Timestamp can be a django model datetime object

**Comment by arunikayadav42** [comment]
if nobidy is working on it i wouod like to take it up :).I ensure to stay consistent while working on it.

**Comment by sumit-badsara** [comment]
@prabhakar267 please assign this issue to me.

**Comment by HemabhKamboj** [comment]
Hey, I am working under GSSoC 19. Is this issue open? If yes, I would like to work on this.

**Comment by Swati4star** [comment]
This isnt open. A PR has already been created for this issue.

**Comment by prabhakar267** [comment]
Closing. No longer needed!
