### ISSUE TITLE
[API Request] Places API

### ISSUE THREAD

**Issue by prabhakar267** [project-travel-mate/server#47]
Call [Here Places API](https://developer.here.com/documentation/places/topics/quick-start-find-text-string.html) to fetch results.
Cache results to serve them faster ([Reference Code](https://github.com/project-travel-mate/server/blob/master/api/modules/city/views.py#L15))
### Input Parameters
+ latitude
+ longitude
+ category_tags

### Output (a list of object, each containing following) 
+ title
+ vicinity (address)
+ href (website)
+ icon

**Comment by Man-Jain** [comment]
I would like to work on this issue.

**Comment by prabhakar267** [comment]
@Man-Jain  sure

**Comment by Man-Jain** [comment]
Can you please tell me where this implementation has to be done and something else for me to get it done.

**Comment by prabhakar267** [comment]
+ Add it as a new module where you call HERE API
+ Create a new serializer, response class and cache the results

**Comment by Man-Jain** [comment]
Sorry @prabhakar267 I will not be able to add this feature.
I did the code for calling the api and the response clasa but couldn't implement the serializer.

**Comment by prabhakar267** [comment]
@Man-Jain if you are facing any problem, everyone would be more than happy to help 😄

**Comment by Man-Jain** [comment]
@prabhakar267 Well I am not at all familier with django models and serialisers so don't know how to implement them. 😅

**Comment by prabhakar267** [comment]
Here you go
https://docs.djangoproject.com/en/2.0/topics/db/models/
http://www.django-rest-framework.org/api-guide/serializers/

Start with these and if you have any query feel free to ping me on slack

**Comment by techac** [comment]
@prabhakar267  can i take up this issue
