### ISSUE TITLE
[API Request] Get friends

### ISSUE THREAD

**Issue by prabhakar267** [project-travel-mate/server#48]
For a given, send a list of all the users, with whom our current user has ever been on trip with.

**Comment by techac** [comment]
I want to work on this issue........
I am planning to implement in trips module and using trip model making the desired api call..

**Comment by techac** [comment]
@prabhakar267  you may review the PR #74  for approval

**Comment by techac** [comment]
@prabhakar267 you may review PR #74

**Comment by prabhakar267** [comment]
@techac I was just adding comments only 
Code looks fine, just a minor code placement change
Update your code and I will be able to merge it 😄
