### ISSUE TITLE
[API Request] Make a call to standard Twitter search API 

### ISSUE THREAD

**Issue by prabhakar267** [project-travel-mate/server#49]
[Twitter Reference Docs](https://developer.twitter.com/en/docs/tweets/search/api-reference/get-search-tweets)
### Input parameters
+ search query

### Output
A list of objects, each containing
+ `created_at`
+ `text `
+ `username`
+ `user_screen_name`
+ `user_profile_image`
+ `retweet_count`
+ `favorite_count`

**Comment by mohitkh7** [comment]
Can I work on this issue ?

**Comment by prabhakar267** [comment]
@mohitkh7 Make a new module and serializer for this task
You will have to move the city trends code to that new module as well
