### ISSUE TITLE
[API Request] Zomato API for nearby food outlets

### ISSUE THREAD

**Issue by prabhakar267** [project-travel-mate/server#50]
Integrate with [Zomato API](https://developers.zomato.com/documentation) to get a list of nearby food outlets and information about them
### Input parameters
+ `latitude`
+ `longitude`

### Output
A list of objects, each containing
+ `restaurant _id`
+ `restaurant_name`
+ `restaurant_url`
+ `restaurant_latitude`
+ `restaurant_longitude`
+ `average_cost_for_two`
+ `currency`
+ `restaurant_image (featured_image)`
+ `aggregate_rating`
+ `votes`
+ `phone_numbers`

**Comment by darthgera123** [comment]
i would like to work on this issue

**Comment by Swati4star** [comment]
@darthgera123 @prabhakar267 What is the endpoint of this API?

**Comment by prabhakar267** [comment]
`get-all-restaurants/<str:latitude>/<str:longitude>`
