### ISSUE TITLE
[API Request] In-app notifications module

### ISSUE THREAD

**Issue by prabhakar267** [project-travel-mate/server#51]
+ Create a new table with notifications information. Every time a user is removed or added to a trip, make an entry to the table with current time, user initiating the flow and relevant text 
+ A GET API to show all the notifications for a given user 
Notification table should have 
+ initiator user
+ destined user
+ trip 
+ timestamp
+ notification text
+ read_unread flag

**Comment by mohitkh7** [comment]
I am interested to work this issue.
