### ISSUE TITLE
[API Request] Update password

### ISSUE THREAD

**Issue by prabhakar267** [project-travel-mate/server#52]
POST API to update user's password. Verify if the old password is correct or not.
If correct, change the password and update the user session.
### Input parameters
+ old password
+ new password

### Output
+ response code

**Comment by akansha006** [comment]
I would like to take up this issue.

**Comment by techac** [comment]
@prabhakar267 i think this issue is no longer in progress so i want to take it as my next issue.
But I have a doubt if it is safe to update password like this? I guess it may cause security breach..

**Comment by prabhakar267** [comment]
@techac Please claim other issues once you are done with the one you are working on.
Raising PR doesn't mean it's complete, you need to wait for the changes to be approved and merged.
There's no point in spamming every issue

**Comment by arunikayadav42** [comment]
@prabhakar267 can i take this one up?

**Comment by prabhakar267** [comment]
@arunikayadav42  sure

**Comment by arunikayadav42** [comment]
@prabhakar267 how do I access the database of users?The sign-in is not working for me thorugh localhost on the browser but it does on postman.

**Comment by arunikayadav42** [comment]
@prabhakar267 i get this "This is a duplicate header and will be overridden by the Authorization header generated by Postman." when i try to put in the authorization token in postman what do i do?
