### ISSUE TITLE
[API Request] Make a GET API to mark one notification as read

### ISSUE THREAD

**Issue by prabhakar267** [project-travel-mate/server#60]
Make a GET API that takes one notification id and marks it as read in database.
Do remember to check if the user is `destined_user` for that particular notification 
### Input Parameters
+ Notification ID

### Output
+ status code

**Comment by mohitkh7** [comment]
Can I work on this issue ?

**Comment by prabhakar267** [comment]
@mohitkh7 Since you have built the notifications module
Can you add similar API for bulk mark as read also that takes a list of notification ids

**Comment by mohitkh7** [comment]
I did this for one id. But not sure how to send multiple ids in url.
One approach can be to send it as 
`api/mark-notification-as-read?id=1&id=2&id=3`
but I don't think it is correct way to do in APIs.

 Another approach can be to have separate view which mark **all unread notification** for a user as read.

**Comment by prabhakar267** [comment]
@mohitkh7 I think it makes sense to have mark all unread notifications API instead of taking a list of ids
Please add that as well.
