### ISSUE TITLE
[Feature Request] Add nicknames to cities 

### ISSUE THREAD

**Issue by knightcube** [project-travel-mate/server#62]
In the main screen with all the cities listed we can show a nickname corresponding to each city. For eg) Bangalore - sillicon valley of India, Kolkata - city of Joy, etc.
A list of nicknames of cities can be found here https://ugcportal.com/raman-files/Nicknames-of-Indian-Cities.pdf

Make a new model with nicknames information and make relevant changes to [CitySerializer](https://github.com/project-travel-mate/server/blob/master/api/modules/city/serializers.py#L23). Also write a temporary endpoint script which can be used to populate these names

**Comment by arunikayadav42** [comment]
I would want to take up this issue as my next task :)

**Comment by darthgera123** [comment]
if no one has taken up ill take the issue

**Comment by mohitkh7** [comment]
I would like to work on this issue.
Rather than creating new model for nickname we can create a new field `nickname` in `City` model.
