### ISSUE TITLE
[Feature Request] Best time to visit

### ISSUE THREAD

**Issue by knightcube** [project-travel-mate/server#67]
Add the Best time to visit. For eg) Manali -  October to February

**Comment by prabhakar267** [comment]
@knightcube how do you plan on adding data for this?

**Comment by knightcube** [comment]
Hardcode data like - From month A to month B

**Comment by knightcube** [comment]
But still there is another way we can do this. I mean we can generate a Poll quiz for the users where we can get the responses and then according to that update the database for this feature?

**Comment by prabhakar267** [comment]
@knightcube so before we go ahead and implement "Best time to visit" feature, we should be considering the "poll quiz" feature

**Comment by knightcube** [comment]
Yeah
