### ISSUE TITLE
[Feature Request] Add ways to reach a particular location

### ISSUE THREAD

**Issue by knightcube** [project-travel-mate/server#68]
For eg) 
How to reach
By air: Located at a distance of about 52 kms, Kullu-Manali airport is the nearest airport to Manali.
By rail: Joginder Nagar is the nearest railway station to Manali located at a distance of about 160 kms.
By road: Manali can be easily reach by road via private cabs, cars, and state-run or private buses from the nearby cities of New Delhi, Chandigarh, Pathankot, Ambala, and so on

**Comment by prabhakar267** [comment]
@knightcube how do you plan on adding data for this?

**Comment by darthgera123** [comment]
i think this can be solved using Google Maps Api where the nearest railway station and airport can be tracked.

**Comment by arunikayadav42** [comment]
if nobody is working on this I would like to take it up.

**Comment by HemabhKamboj** [comment]
If nobody is working, I would like to take this up under GSSoC 19. WIll use Google Maps or MapMyIndia APIs.

**Comment by codersanjeev** [comment]
Hi @HemabhKamboj you can start working on the issue.

**Comment by HemabhKamboj** [comment]
Great, thanks

**Comment by GouravSardana** [comment]
@HemabhKamboj Go ahead and start working with google maps api

**Comment by prabhakar267** [comment]
Google API is a paid service and we plan on keeping Travel-Mate free, hence I don't see any other feasible option to include this feature as of now.
