### ISSUE TITLE
[API Request] Update Profile model to have user status 

### ISSUE THREAD

**Issue by prabhakar267** [project-travel-mate/server#71]
+ Change Profile model to incorporate user status as well
+ Make changes to User serializer to show status
+ Make an API to add/update (both in single api) user status

**Comment by techac** [comment]
@prabhakar267  i am willing to work on this issue but can you explain me what you mean by user status.....

**Comment by prabhakar267** [comment]
@techac Please complete the issue you are already assigned, then you can go for issue-hunting 😄

**Comment by techac** [comment]
@prabhakar267  now can you tell what exactly do you mean by user status

**Comment by prabhakar267** [comment]
A status string

**Comment by Swati4star** [comment]
@prabhakar267 @techac 
Mention the endpoint & parameters required.

**Comment by iamdaaniyaal** [comment]
@prabhakar267 I would like to work on this if this issue is not taken up by someone

**Comment by prabhakar267** [comment]
@iamdaaniyaal It's already closed
You can have a look at other open issues
