### ISSUE TITLE
[API Request] Remove profile picture API

### ISSUE THREAD

**Issue by prabhakar267** [project-travel-mate/server#76]
GET API to remove current profile picture for the user. It shouldn't take any input parameters, use the `request.user` information to remove profile picture from `Profile` table
Note: If the `Profile` table doesn't have any entry, do make an entry to `Profile` table

**Comment by mohitkh7** [comment]
Can I take up this issue ?

**Comment by Swati4star** [comment]
@prabhakar267 @mohitkh7 What is the final endpoint & input parameters for this API?

**Comment by mohitkh7** [comment]
final endpoint is _/api/remove-profile-image_ 
And It doesn't requires any input parameter.

**Comment by Swati4star** [comment]
Thanks! 👍
