### ISSUE TITLE
[API request] Get city names for autocomplete

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/server#8]
Add a new API to get the list of the cities whose name start with a given word (received as input to the API). 
Each city entry should have following information: 
- City id
- City name

**Comment by mohitkh7** [comment]
I am interested to work on this issue.

**Comment by prabhakar267** [comment]
@mohitkh7 This has been already fixed in bd04ecfe3d80fce6dace85f2af1c3d761e5a89bf 
Sorry, didn't close this.
You can work on [other open issues](https://github.com/project-travel-mate/server/issues).
