### ISSUE TITLE
[API Request] Get common trips with a friend 

### ISSUE THREAD

**Issue by prabhakar267** [project-travel-mate/server#86]
For a given user, return a list of trips that are common between the given user and the current signed-in user
### Input parameters
+ User ID
### Output
+ List of common trips

**Comment by mohitkh7** [comment]
I am interested to work on this issue.

**Comment by mohitkh7** [comment]
What should be the response if input paramter _User_ID_ is same as _current signed-in user ID_

Shall It return error or all trip with which he is associated ?

**Comment by prabhakar267** [comment]
You can send a `400` response code
