### ISSUE TITLE
[API Request] API to get currency conversion history

### ISSUE THREAD

**Issue by prabhakar267** [project-travel-mate/server#87]
Use [Historical currency converter web service](http://currencies.apps.grandtrunk.net/) to get information about currency rates history. Use **List of historical conversion rates** API ([Reference response](http://currencies.apps.grandtrunk.net/getrange/1999-01-01/2000-01-01/eur/usd)).
Currently the API collapses the conversion rates that are same, you need to return a conversion rate for each day.
Do check if from date is before to date. 
Return a 400 response if currency code is incorrect which you can know from API response
### Input Parameters
+ from date (in YYYY-MM-DD format)
+ to date (in YYYY-MM-DD format)
+ from currency code (three digit currency code)
+ to currency code (three digit currency code)
### Output
+ List of currency conversion rates (length of list should be equal to the number of days between to-date and from-date)

**Comment by darthgera123** [comment]
can i work on this issue

**Comment by darthgera123** [comment]
do you want me to return the date as well

**Comment by darthgera123** [comment]
also how do i test now. Its opening the github page link on localhost
