### ISSUE TITLE
[API Request] Remove user status

### ISSUE THREAD

**Issue by Swati4star** [project-travel-mate/server#89]
GET API to remove status for a given user. It shouldn't take any input parameters, use the `request.user` information to remove status from `Profile` table
Note: If the `Profile` table doesn't have any entry, do make an entry to `Profile` table
Reference Issue #76

**Comment by techac** [comment]
@Swati4star  i would like to take up this issue

**Comment by Swati4star** [comment]
@prabhakar267 ...
