### ISSUE TITLE
Add validations for password

### ISSUE THREAD

**Issue by prabhakar267** [project-travel-mate/server#9]
Currently there are no checks on format of the password, we simply assume a plain text string and store it as a hash in DB. Password must contain minimum 8 characters, at least 1 Alphabet, 1 Number and 1 Special Character.
Send a 400 BAD_REQUEST response in `sign-up` API if these criterion are not met.

**Comment by nickgr123** [comment]
Created my first open source pull request for this issue!

**Comment by prabhakar267** [comment]
Closed by #10
