### ISSUE TITLE
[API Request] Remove user from trip

### ISSUE THREAD

**Issue by prabhakar267** [project-travel-mate/server#94]
A GET API similar to [`remove-friend-from-trip`](https://github.com/project-travel-mate/server/blob/master/api/urls.py#L55) but to remove the current signed-in user. Do check 
+ User is a part of the trip
+ If user is the last one in the trip, do **delete** the trip 
### Input parameters
+ trip-id
### Output
+ Status code

**Comment by mohitkh7** [comment]
@prabhakar267 I am interested to work on this issue.
